### ISSUE TITLE
MapRow does not preserve header order

### ISSUE THREAD

**Issue by 5outh** [ozataman/csv-conduit#40]
With the given input file:

```csv
b,a
1,foo
```

Running this program:

```haskell
myProcessor :: MonadIO m => ConduitT (MapRow Text) (MapRow Text) m ()
myProcessor = CC.filter id

runResourceT
    $ runConduit
    $ CC.sourceFile "in.csv"
    .| intoCSV defCSVSettings
    .| myProcessor
    .| (writeHeaders defCSVSettings >> fromCSV defCSVSettings)
    .| CC.sinkFile "out.csv"
```

outputs the following to `out.csv`:

```csv
a,b
foo,1
```

It would be nice to preserve the ordering as determined by the header, or at least have the option to do so.

**Comment by ysangkok** [comment]
It just bit me that `rowToStr` also is affected by this, subsequent calls to it are technically not guaranteed to have the same order...

I wish `NamedRecord` was an OrderedMap instead. I order the keys when I pass them to `namedRecord`...

**Comment by MichaelXavier** [comment]
I would accept an MR to use probably [https://hackage.haskell.org/package/ordered-containers] to solve this problem. The impact seems significant enough that it would be worth making a breaking change than to try to preserve the old behavior. I can't imagine anyone is relying on the current implementation to put the keys in alphabetical order because that's how Map stores them.
